workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

codspeed:
  stage: test
  image: rust
  variables:
    CODSPEED_LOG: trace
    CODSPEED_RUNNER_VERSION: 3.1.1-beta.1
    RUSTFLAGS: -C embed-bitcode -D warnings
  before_script:
    - cd py-polars
    - apt-get update -y
    - apt-get install -y build-essential python3-dev libxml2-dev libxslt-dev
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - source $HOME/.local/bin/env
    - uv venv --python 3.12
    - uv pip install --compile-bytecode -r requirements-dev.txt -r requirements-ci.txt --verbose
    - curl -fsSL https://github.com/CodSpeedHQ/runner/releases/download/v$CODSPEED_RUNNER_VERSION/codspeed-runner-installer.sh | bash -s -- --quiet
    - source $HOME/.cargo/env
  script:
    - maturin develop --release -- -C codegen-units=8 -C lto=thin -C target-cpu=native
    - codspeed run --upload-url="$CODSPEED_UPLOAD_URL" -- pytest -m benchmark --codspeed -v
